index:
  path: /index
  controller: App\Controller\IndexController::index

home:
  path: /home
  controller: App\Controller\DefaultController::index

admin:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index

